libs2e: run target configurations in parallel
Signed-off-by: Vitaly Chipounov <vitaly@cyberhaven.io>

diff --git a/libs2e/configure b/libs2e/configure
--- a/libs2e/configure
+++ b/libs2e/configure
@@ -212,7 +212,10 @@ LIBCPU_REVISION="$(get_git_revision)"
 # Configuring each target
 #################################################################
 
-for target in i386-softmmu i386-s2e-softmmu i386-s2e_sp-softmmu x86_64-softmmu x86_64-s2e-softmmu x86_64-s2e_sp-softmmu; do
+configure_target() {
+
+local target="$1"
+
 echo "============== Configuring $target ============== "
 echo
 
@@ -259,6 +262,7 @@ cmake -DCMAKE_C_COMPILER="$CC" -DCMAKE_CXX_COMPILER="$CXX"      \
     -DLIBQ_DIR=$LIBQ_DIR                                        \
     -DLLVM_DIR="$LLVM_DIR" "$LIBTCG_SRC"
 if [ $? -ne 0 ]; then
+  >&2 echo "Failed to configure libtcg"
   exit 1
 fi
 cd ..
@@ -282,6 +286,7 @@ cmake -DCMAKE_C_COMPILER="$CC" -DCMAKE_CXX_COMPILER="$CXX"  \
     "$LIBCPU_SRC"
 
 if [ $? -ne 0 ]; then
+  >&2 echo "Failed to configure libcpu"
   exit 1
 fi
 cd ..
@@ -298,13 +303,13 @@ cmake -DCMAKE_C_COMPILER="$CC" -DCMAKE_CXX_COMPILER="$CXX"  \
     -DLIBCPU_DIR="$(pwd)/../libcpu"                         \
     -DLLVM_DIR="$LLVM_DIR"                                  \
     -DKLEE_DIR="$KLEE_ROOT"                                 \
-    -DVMI_DIR="$LIBVMI_DIR"                                 \
     -DFSIGCXX_DIR="$FSIGCXX_DIR"                            \
     -DLIBQ_DIR="$LIBQ_DIR"                                  \
     -DLUA_DIR="$LIBLUA_LIB"                                 \
     "$LIBS2ECORE_SRC"
 
 if [ $? -ne 0 ]; then
+  >&2 echo "Failed to configure libs2ecore"
   exit 1
 fi
 cd ..
@@ -330,6 +335,7 @@ cmake -DCMAKE_C_COMPILER="$CC" -DCMAKE_CXX_COMPILER="$CXX"  \
     "$LIBS2EPLUGINS_SRC"
 
 if [ $? -ne 0 ]; then
+  >&2 echo "Failed to configure libs2eplugins"
   exit 1
 fi
 cd ..
@@ -360,11 +366,24 @@ cmake -DCMAKE_C_COMPILER="$CC" -DCMAKE_CXX_COMPILER="$CXX"  \
     "$SRC_DIR"
 
 if [ $? -ne 0 ]; then
+  >&2 echo "Failed to configure libs2e"
   exit 1
 fi
 cd ..
 
 
 echo "============== Configuring $target done ============== "
+}
 
+TARGETS="i386-softmmu i386-s2e-softmmu i386-s2e_sp-softmmu x86_64-softmmu x86_64-s2e-softmmu x86_64-s2e_sp-softmmu"
+
+for target in $TARGETS; do
+    rm -f ${target}.log
 done
+
+for target in $TARGETS; do
+    echo "Configuring $target..."
+    configure_target $target 2>&1 > ${target}.log &
+done
+
+wait
